# Generated by ariadne-codegen
# Source: gql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GenerateSecretKey(BaseModel):
    regenerate_secret_key: Optional["GenerateSecretKeyRegenerateSecretKey"] = Field(
        alias="regenerateSecretKey"
    )


class GenerateSecretKeyRegenerateSecretKey(BaseModel):
    viewer: Optional["GenerateSecretKeyRegenerateSecretKeyViewer"]


class GenerateSecretKeyRegenerateSecretKeyViewer(BaseModel):
    live_secret_key: Optional[str] = Field(alias="liveSecretKey")
