# Generated by ariadne-codegen
# Source: gql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetKrakenToken(BaseModel):
    obtain_kraken_token: Optional["GetKrakenTokenObtainKrakenToken"] = Field(
        alias="obtainKrakenToken"
    )


class GetKrakenTokenObtainKrakenToken(BaseModel):
    token: str
    refresh_token: Optional[str] = Field(alias="refreshToken")
    refresh_expires_in: Optional[int] = Field(alias="refreshExpiresIn")
