query accountAgreementAndMeterDetails($account: String!) {
  account(accountNumber:$account){
    electricityAgreements(active:true){
      id,
      validTo,
      validFrom,
      tariff{
        __typename
        ... on StandardTariff{
            id
            productCode
            standingCharge
            unitRate
        }
        ... on TariffType {
            id
            productCode
            standingCharge
        }
      }
      meterPoint{
        id
        mpan
        status
        meters(includeInactive: false){
          serialNumber
          smartDevices {
            id
            deviceId
            serialNumber
          }
        }
      }
    }
    campaigns{
      name
    }
  }
}