query getAccountInfo {
    viewer {
        givenName
        familyName
        email
        liveSecretKey
        accounts(restrictToPublicFacingBrands: false) {
            number, status, balance, brand
        }
    }
}